version: '3.1'

services:

  db:
    build: db
    container_name: test_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dvdrental
    ports:
      - 5432:5432
  rd:
    build: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning --requirepass 123456